language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install -y m4 autoconf automake

script:
  - |
    export CFLAGS=-Werror && \
    ./configure && make && make distclean && \
    scan-build ./configure && \
    scan-build --status-bugs make
