language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script:
  - |
    autoreconf --force && \
    \
    ./configure && \
    make "CFLAGS=-Werror" && \
    make distclean && \
    \
    scan-build ./configure && \
    scan-build --status-bugs make "CFLAGS=-std=gnu99 -Werror"
