language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  - windows

stages:
  - name: test
    if: os != windows
  - name: cygwin
    if: os = windows
  - name: analysis
    if: os = linux

script:
  - autoreconf --force && ./configure && make "CFLAGS=-Werror"

jobs:
  include:
    - stage: cygwin
      if: os = windows
      install:
        - choko install cygwin --params "/InstallDir:%LOCALAPPDATA% /NoStartMenu"
      script:
        - echo OK
    - stage: analysis
      if: os = linux
      script:
        - autoreconf --force && scan-build ./configure && scan-build --status-bugs make "CFLAGS=-std=gnu99 -Werror"
