language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

jobs:
  include:
    - stage: build
      script: autoreconf --force && ./configure && make "CFLAGS=-Werror"
    - if: os = linux
      stage: analysis
      script: autoreconf --force && scan-build ./configure && scan-build --status-bugs make "CFLAGS=-std=gnu99 -Werror"
