language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  - windows

addons:
  sonarcloud:
    organization: "oleg-derevenetz-github"
    token:
      secure: "WjJXzm6W1bKx3wSLh1K2t8fByxh8j7NNrHTmjC7NtN522BRZnGYOnPjabozRnZ8qR1CNhBFG+X/4pzvrvccBCi1hs8MjihHwH2gUMcLpq9upWhZiRVmt7IKSSMHswOv6rTL0mvPLefdaTh0JI5PVBqWwkmKQvxqHDdWlO9GiA1jAV4DrIc4DqgekXooEDrJ6BNrF80x0O0pJSdXQPnNo4bkD5i/tQQPeTY7KHtojKVXxZCLUMu5GySTj6rWk4wMtte56yJqzflwU6BIC93sIxc1gD0IVq1lsUGxbaaUqNMZbpu4xnhbfRzzSLaTcS/fB/kgEY1afEGiNVE47IqhUpCYPCesgLBcx5kFqoi//+Py0zAsk2EM/elrY+jUU4QpA13+pT73TRBVMPh/DHk8mQax25y8QHXxJDWigv19ci80JVKPfRJHRd9t8p1qrrPbmIdgC6AjYswvlimUrYY+8ZiuGKt1OZ3EHSrv6LewBxoVAw/CVsXZMsV1Cp/NV8wkcyPNiTlug5oah6T6EcUPmsNemun8bEoWrQ7FLZXMp1mcBlp91GWf+hFdmGd3onyr+WCo9qEtPz8cC/P30wlW4AVX4bSRHFt0GiHyl8Un1kLfPCoc1SwXZ7r5Afc97fbX1nEgvnxCwIMzmkWDEjXlQkIv48Il5wEe032WY/n/8+jU="

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        echo && \
        echo "---- INSTALLATION OF CYGWIN AND CYG-GET ---" && \
        echo && \
        choco install cygwin cyg-get && \
        echo && \
        echo "----- INSTALLATION OF CYGWIN PACKAGES -----" && \
        echo && \
        C:\\ProgramData\\chocolatey\\bin\\cyg-get.bat autoconf automake make gcc-core clang clang-analyzer git && \
        echo && \
        echo "----------- END OF INSTALLATION -----------" && \
        echo
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        STATUS=1

        if [[ "$CC" == "clang" ]]; then
            echo && \
            echo "----------- AUTORECONF --FORCE ------------" && \
            echo && \
            autoreconf --force && \
            echo && \
            echo "---------------- CONFIGURE ----------------" && \
            echo && \
            ./configure && \
            echo && \
            echo "------------------ MAKE -------------------" && \
            echo && \
            make "CFLAGS=-Werror" && \
            echo && \
            echo "--------------- MAKE CHECK ----------------" && \
            echo && \
            sudo make check "TESTS=tests/bwping" && \
            echo && \
            echo "------------- MAKE DISTCLEAN --------------" && \
            echo && \
            make distclean && \
            echo && \
            echo "---------- SCAN-BUILD CONFIGURE -----------" && \
            echo && \
            scan-build ./configure && \
            echo && \
            echo "------------- SCAN-BUILD MAKE -------------" && \
            echo && \
            scan-build --status-bugs make "CFLAGS=-std=gnu99 -Werror"

            STATUS=$?
        else
            echo && \
            echo "----------- AUTORECONF --FORCE ------------" && \
            echo && \
            autoreconf --force && \
            echo && \
            echo "---------------- CONFIGURE ----------------" && \
            echo && \
            ./configure && \
            echo && \
            echo "------------------ MAKE -------------------" && \
            echo && \
            make "CFLAGS=-Werror" && \
            echo && \
            echo "--------------- MAKE CHECK ----------------" && \
            echo && \
            sudo make check "TESTS=tests/bwping" && \
            echo && \
            echo "-------------- SONAR WRAPPER --------------" && \
            echo && \
            build-wrapper-linux-x86-64 --out-dir bw-output make clean all && \
            echo && \
            echo "-------------- SONAR SCANNER --------------" && \
            echo && \
            sonar-scanner

            STATUS=$?
        fi

        if [[ -f config.log ]]; then
            echo
            echo "----------- BEGIN OF CONFIG.LOG -----------"
            echo
            cat config.log
            echo
            echo "------------ END OF CONFIG.LOG ------------"
            echo
        fi
        if [[ -f test-suite.log ]]; then
            echo
            echo "--------- BEGIN OF TEST-SUITE.LOG ---------"
            echo
            cat test-suite.log
            echo
            echo "---------- END OF TEST-SUITE.LOG ----------"
            echo
        fi

        exit $STATUS
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo && \
        echo "----------- AUTORECONF --FORCE ------------" && \
        echo && \
        autoreconf --force && \
        echo && \
        echo "---------------- CONFIGURE ----------------" && \
        echo && \
        ./configure && \
        echo && \
        echo "------------------ MAKE -------------------" && \
        echo && \
        make "CFLAGS=-Werror" && \
        echo && \
        echo "--------------- MAKE CHECK ----------------" && \
        echo && \
        sudo make check

        STATUS=$?

        if [[ -f config.log ]]; then
            echo
            echo "----------- BEGIN OF CONFIG.LOG -----------"
            echo
            cat config.log
            echo
            echo "------------ END OF CONFIG.LOG ------------"
            echo
        fi
        if [[ -f test-suite.log ]]; then
            echo
            echo "--------- BEGIN OF TEST-SUITE.LOG ---------"
            echo
            cat test-suite.log
            echo
            echo "---------- END OF TEST-SUITE.LOG ----------"
            echo
        fi

        exit $STATUS
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        GIT_REPO_URL="https://github.com/oleg-derevenetz/bwping.git"
        GIT_REPO_BRANCH="master"

        STATUS=1

        if [[ "$CC" == "clang" ]]; then
            mkdir -p "$TRAVIS_BUILD_DIR/_CYGWIN_" && \
            C:\\tools\\cygwin\\bin\\bash.exe -l -c " \
                echo && \
                echo \"------------------ SETUP ------------------\" && \
                echo && \
                export CC=\"$CC\" && \
                cd \"/cygdrive/$TRAVIS_BUILD_DIR/_CYGWIN_\" && \
                echo && \
                echo \"---------------- GIT CLONE ----------------\" && \
                echo && \
                git clone --depth=50 --branch=\"$GIT_REPO_BRANCH\" \"$GIT_REPO_URL\" . && \
                echo && \
                echo \"----------- AUTORECONF --FORCE ------------\" && \
                echo && \
                autoreconf --force && \
                echo && \
                echo \"---------------- CONFIGURE ----------------\" && \
                echo && \
                ./configure && \
                echo && \
                echo \"------------------ MAKE -------------------\" && \
                echo && \
                make \"CFLAGS=-Werror\" && \
                echo && \
                echo \"--------------- MAKE CHECK ----------------\" && \
                echo && \
                make check && \
                echo && \
                echo \"------------- MAKE DISTCHECK --------------\" && \
                echo && \
                make distcheck && \
                echo && \
                echo \"------------- MAKE DISTCLEAN --------------\" && \
                echo && \
                make distclean && \
                echo && \
                echo \"---------- SCAN-BUILD CONFIGURE -----------\" && \
                echo && \
                scan-build ./configure && \
                echo && \
                echo \"------------- SCAN-BUILD MAKE -------------\" && \
                echo && \
                scan-build --status-bugs make \"CFLAGS=-std=gnu99 -Werror\""

            STATUS=$?
        else
            mkdir -p "$TRAVIS_BUILD_DIR/_CYGWIN_" && \
            C:\\tools\\cygwin\\bin\\bash.exe -l -c " \
                echo && \
                echo \"------------------ SETUP ------------------\" && \
                echo && \
                export CC=\"$CC\" && \
                cd \"/cygdrive/$TRAVIS_BUILD_DIR/_CYGWIN_\" && \
                echo && \
                echo \"---------------- GIT CLONE ----------------\" && \
                echo && \
                git clone --depth=50 --branch=\"$GIT_REPO_BRANCH\" \"$GIT_REPO_URL\" . && \
                echo && \
                echo \"----------- AUTORECONF --FORCE ------------\" && \
                echo && \
                autoreconf --force && \
                echo && \
                echo \"---------------- CONFIGURE ----------------\" && \
                echo && \
                ./configure && \
                echo && \
                echo \"------------------ MAKE -------------------\" && \
                echo && \
                make \"CFLAGS=-Werror\" && \
                echo && \
                echo \"--------------- MAKE CHECK ----------------\" && \
                echo && \
                make check && \
                echo && \
                echo \"------------- MAKE DISTCHECK --------------\" && \
                echo && \
                make distcheck"

            STATUS=$?
        fi

        if [[ -f "$TRAVIS_BUILD_DIR/_CYGWIN_/config.log" ]]; then
            echo
            echo "----------- BEGIN OF CONFIG.LOG -----------"
            echo
            cat "$TRAVIS_BUILD_DIR/_CYGWIN_/config.log"
            echo
            echo "------------ END OF CONFIG.LOG ------------"
            echo
        fi
        if [[ -f "$TRAVIS_BUILD_DIR/_CYGWIN_/test-suite.log" ]]; then
            echo
            echo "--------- BEGIN OF TEST-SUITE.LOG ---------"
            echo
            cat "$TRAVIS_BUILD_DIR/_CYGWIN_/test-suite.log"
            echo
            echo "---------- END OF TEST-SUITE.LOG ----------"
            echo
        fi

        exit $STATUS
    fi
