language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script:
  - autoreconf --force && ./configure && make "CFLAGS=-Werror"

jobs:
  include:
    - stage: analysis
      if: os = linux
      script:
        - autoreconf --force && scan-build ./configure && scan-build --status-bugs make "CFLAGS=-std=gnu99 -Werror"
