language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

stages:
  - name: analysis
    if: os = linux

jobs:
  include:
    - stage: analysis
      script: autoreconf --force && scan-build ./configure && scan-build --status-bugs make "CFLAGS=-std=gnu99 -Werror"

script:
  - autoreconf --force && ./configure && make "CFLAGS=-Werror"
