language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  - windows

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        choco install cygwin cyg-get && \
        C:\\ProgramData\\chocolatey\\bin\\cyg-get.bat perl m4 autoconf automake gcc-core clang
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        autoreconf --force && \
        ./configure && make "CFLAGS=-Werror" && make distclean && \
        scan-build ./configure && scan-build --status-bugs make "CFLAGS=-std=gnu99 -Werror"
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        autoreconf --force && \
        ./configure && make "CFLAGS=-Werror"
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        pwd
        ls -l
        CYGWIN_BUILD_DIR="/c/tools/cygwin/home/$USER/build" && \
        mkdir "$CYGWIN_BUILD_DIR" && cp -PR * "$CYGWIN_BUILD_DIR"
        ls -l
        ls -l /c/tools/cygwin
        echo "$CYGWIN_BUILD_DIR" && cd "$CYGWIN_BUILD_DIR" && ls -l
        echo $CC
        echo OK
    fi
