language: c

before_install:
  - sudo apt-get update
  - sudo apt-get install -y m4 autoconf automake

script:
  - |
    ./configure && make "CFLAGS=-Werror" && make distclean && \
    scan-build ./configure && \
    scan-build --status-bugs make "CFLAGS=-std=gnu99 -Werror"
