name: "Clang Analysis"

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

  schedule:
  - cron: "0 11 * * 6"

jobs:
  clang:
    name: "Clang Analysis (--${{ matrix.mmsg }} --${{ matrix.bpf }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mmsg:
        - enable-mmsg
        - disable-mmsg
        bpf:
        - enable-bpf
        - disable-bpf

    defaults:
      run:
        shell: bash

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v2

    - name: "Install additional packages"
      run: |
        sudo apt-get -y update
        sudo apt-get -y install autoconf automake clang-tools

    - name: "Perform Clang analysis"
      run: |
        autoreconf -f -i -Wall,error
        scan-build ./configure --${{ matrix.mmsg }} --${{ matrix.bpf }}
        scan-build --status-bugs make "CFLAGS=-std=c11 -Werror"
