name: "Clang Analysis"

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

  schedule:
  - cron: "0 11 * * 6"

jobs:
  clang:
    name: "Clang Analysis (${{ matrix.config.name }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
        - { name: "default",         options: "" }
        - { name: "no mmsg",         options: "--disable-mmsg" }
        - { name: "no bpf",          options: "--disable-bpf" }
        - { name: "no mmsg, no bpf", options: "--disable-mmsg --disable-bpf" }

    defaults:
      run:
        shell: bash

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: "Checkout HEAD^2 for pull request"
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        git checkout HEAD^2

    - name: "Install additional packages"
      run: |
        sudo apt-get update
        sudo apt-get -y install autoconf automake clang-tools

    - name: "Perform Clang analysis"
      run: |
        autoreconf -f -i -Wall,error
        scan-build ./configure ${{ matrix.config.options }}
        scan-build --status-bugs make "CFLAGS=-std=c11 -Werror"
